config/routes.rb
Zavod::Application.routes.draw do
	match '/contact', :to => 'pages#contact'

	match '/about',   :to => 'pages#about'

	root :to => 'pages#home'

	get "reports/parts"

	get "reports/deliveries"

	resources :suppliers do
		resources :parts
	end

	resources :products do
		resources :parts #, :except => [ :edit, :new, :create, :destroy, :update ]
		member do
			get :add_part
			put :assign_part, :free_part
		end
	end

	resources :factories do
		resources :departments do
			resources :products
		end
	end

end

app/models/part.rb
# == Schema Information
#
# Table name: parts
#
#  id            :integer(4)      not null, primary key
#  part_number   :integer(4)
#  name          :string(255)
#  product_id    :integer(4)
#  weight        :integer(10)
#  dimensions    :string(255)
#  supplier_id   :integer(4)
#  delivery_date :date
#  created_at    :datetime        not null
#  updated_at    :datetime        not null
#

class Part < ActiveRecord::Base
	belongs_to :product
	belongs_to :supplier

	validates :name, :presence => true
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
	# GET /parts
	# GET /parts.json
	def index
# 		@product = Product.find(params[:product_id])
 		@supplier = Supplier.find(params[:supplier_id])
		@parts = @supplier.parts
		
		respond_to do |format|
		format.html # index.html.erb
		format.json { render json: @parts }
		end
	end

	# GET /parts/1
	# GET /parts/1.json
	def show
		@part = Part.find(params[:id])
# 		@product = Product.find(@part.product_id)
		@supplier = Supplier.find(@part.supplier_id)
		
		respond_to do |format|
		format.html # show.html.erb
		format.json { render json: @part }
		end
	end

	# GET /parts/new
	# GET /parts/new.json
	def new
		@part = Part.new
# 		@product = Product.find(@part.product_id)
		@supplier = Supplier.find(params[:supplier_id])
		
		respond_to do |format|
		format.html # new.html.erb
		format.json { render json: @part }
		end
	end

	# GET /parts/1/edit
	def edit
		@part = Part.find(params[:id])
		@product = Product.find(@part.product_id)
		@supplier = Supplier.find(@part.supplier_id)
	end

	# POST /parts
	# POST /parts.json
	def create
		@part = Part.new(params[:part])
# 		@product = Product.find(@part.product_id)
		@supplier = Supplier.find(params[:supplier_id])
		
		respond_to do |format|
		if @part.save
			format.html { redirect_to @supplier, notice: t('actions.part.notice.created') }
			format.json { render json: @part, status: :created, location: @supplier }
		else
			format.html { render action: "new" }
			format.json { render json: @part.errors, status: :unprocessable_entity }
		end
		end
	end

	# PUT /parts/1
	# PUT /parts/1.json
	def update
		@part = Part.find(params[:id])
# 		@product = Product.find(@part.product_id)
		@supplier = Supplier.find(@part.supplier_id)
		
		respond_to do |format|
		if @part.update_attributes(params[:part])
			format.html { redirect_to @supplier, notice: t('actions.part.notice.updated') }
			format.json { head :no_content }
		else
			format.html { render action: "edit" }
			format.json { render json: @part.errors, status: :unprocessable_entity }
		end
		end
	end

	# DELETE /parts/1
	# DELETE /parts/1.json
	def destroy
		@part = Part.find(params[:id])
# 		@product = Product.find(@part.product_id)
		@supplier = Supplier.find(@part.supplier_id)
		@part.destroy

		respond_to do |format|
			format.html { redirect_to @supplier }
			format.json { head :no_content }
		end
	end
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/parts/_form.html.erb
<%= form_for([@supplier, @part]) do |f| %>
  <%= f.error_messages :class =>  "error_explanation",  :id => "error_explanation" %>
  <div class="field">
    <%= f.label :part_number %><br />
    <%= f.number_field :part_number %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
<!--  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>-->
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :dimensions %><br />
    <%= f.text_field :dimensions %>
  </div>
<!--  <div class="field">
    <%= f.label :supplier_id %><br />
    <%= f.number_field :supplier_id %>
  </div>-->
  <%= f.hidden_field :supplier_id, :value => @supplier.id %>
  <div class="field">
    <%= f.label :delivery_date %><br />
    <%= f.date_select :delivery_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parts/_part.html.erb
<tr>
	<td><%= part.part_number %></td>
	<td><%= part.name %></td>
	<td><%= if part.product then part.product.name else t('none') end %></td>
	<td><%= part.weight %></td>
	<td><%= part.dimensions %></td>
<!-- 	<td><%= if part.supplier then part.supplier.name else t('none') end %></td> -->
	<td><%= l part.delivery_date %></td>
	<td><%= link_to t('links.show'), supplier_part_path(part.supplier_id, part) %></td>
	<td><%= link_to t('links.edit'), edit_supplier_part_path(part.supplier_id, part) %></td>
	<td><%= link_to t('links.delete'), supplier_part_path(part.supplier_id, part), confirm: t( 'actions.confirm'), method: :delete %></td>
</tr>

app/views/parts/edit.html.erb
<h1><%= t('actions.part.edit', :item => @part.name ) %></h1>

<%= render 'form' %>

<%= link_to t('links.show'), supplier_part_path(@part.supplier_id, @part.id) %> |
<%= link_to t('links.back'), supplier_path(@part.supplier_id) %>

app/views/parts/index.html.erb
<h1><%= t('actions.part.index', :item => @supplier.name ) %></h1>

<% if @parts.empty? %>
<p>None</p>
<% else %>
<table>
  <tr>
    <th><%= t('activerecord.attributes.part.part_number') %></th>
    <th><%= t('activerecord.attributes.part.name') %></th>
    <th><%= t('activerecord.attributes.part.product_id') %></th>
    <th><%= t('activerecord.attributes.part.weight') %></th>
    <th><%= t('activerecord.attributes.part.dimensions') %></th>
<!--     <th><%= t('activerecord.attributes.part.supplier_id') %></th> -->
    <th><%= t('activerecord.attributes.part.delivery_date') %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @parts.each do |part| %>
  <tr>
    <td><%= part.part_number %></td>
    <td><%= part.name %></td>
	<td><%= if part.product then part.product.name else 'None' end %></td>
	<td><%= part.weight %></td>
	<td><%= part.dimensions %></td>
<!-- 	<td><%= if part.supplier then part.supplier.name else 'None' end %></td> -->
    <td><%= l part.delivery_date %></td>
	<td><%= link_to t('links.show'), supplier_part_path(part.supplier_id, part) %></td>
	<td><%= link_to t('links.edit'), edit_supplier_part_path(part.supplier_id, part) %></td>
	<td><%= link_to t('links.delete'), supplier_part_path(part.supplier_id, part), confirm: t('actions.confirm'), method: :delete %></td>
  </tr>
<% end %>
</table>
<% end %>

<br />
<%= link_to t('actions.part.new', :item => ''), new_supplier_part_path(@supplier.id) %>

app/views/parts/new.html.erb
<h1><%= t('actions.part.new', :item => @supplier.name) %></h1>

<%= render 'form' %>

<%= link_to t('links.back'), supplier_path(@supplier.id) %>

app/views/parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= t('activerecord.attributes.part.part_number') %>:</b>
  <%= @part.part_number %>
</p>

<p>
  <b><%= t('activerecord.attributes.part.name') %>:</b>
  <%= @part.name %>
</p>

<p>
  <b><%= t('activerecord.attributes.part.product_id') %>:</b>
  <%= if @part.product then @part.product.name else 'None' end %>
</p>

<p>
  <b><%= t('activerecord.attributes.part.weight') %>:</b>
  <%= @part.weight %>
</p>

<p>
  <b><%= t('activerecord.attributes.part.dimensions') %>:</b>
  <%= @part.dimensions %>
</p>

<p>
  <b><%= t('activerecord.attributes.part.supplier_id') %>:</b>
  <%= if @part.supplier then @part.supplier.name else 'None' end %>
</p>

<p>
  <b><%= t('activerecord.attributes.part.delivery_date') %>:</b>
<!--   <%= @part.delivery_date.to_date.to_s(:rfc822) %> -->
<!--   <%= @part.delivery_date.strftime("%d.%m.%Y") %> -->
	<%= l @part.delivery_date %>
</p>


<%= link_to t('actions.edit'), edit_supplier_part_path(@part.supplier_id, @part.id) %> |
<%= link_to t('actions.back'), :back %> <!-- supplier_path(@part.supplier_id) -->