config/routes.rb
Zavod::Application.routes.draw do
	match '/contact', :to => 'pages#contact'

	match '/about',   :to => 'pages#about'

	root :to => 'pages#home'

	get "reports/parts"

	get "reports/deliveries"

	resources :suppliers do
		resources :parts
	end

	resources :products do
		resources :parts #, :except => [ :edit, :new, :create, :destroy, :update ]
		member do
			get :add_part
			put :assign_part, :free_part
		end
	end

	resources :factories do
		resources :departments do
			resources :products
		end
	end

end

app/models/factory.rb
# == Schema Information
#
# Table name: factories
#
#  id         :integer(4)      not null, primary key
#  factory_id :integer(4)
#  name       :string(255)
#  address    :string(255)
#  ceo_name   :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class Factory < ActiveRecord::Base
	has_many :departments, :dependent => :destroy
	
	validates :name, :presence => true
	validates :address, :presence => true
	validates :ceo_name, :presence => true
	validates :factory_num, :presence => true
end

app/controllers/factories_controller.rb
class FactoriesController < ApplicationController
  # GET /factories
  # GET /factories.json
  def index
    @factories = Factory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @factories }
    end
  end

  # GET /factories/1
  # GET /factories/1.json
  def show
    @factory = Factory.find(params[:id])
    @departments = @factory.departments.paginate(:page => params[:page])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @factory }
    end
  end

  # GET /factories/new
  # GET /factories/new.json
  def new
    @factory = Factory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @factory }
    end
  end

  # GET /factories/1/edit
  def edit
    @factory = Factory.find(params[:id])
  end

  # POST /factories
  # POST /factories.json
  def create
    @factory = Factory.new(params[:factory])

    respond_to do |format|
      if @factory.save
		  format.html { redirect_to @factory, notice: t('actions.factory.notice.created') }
        format.json { render json: @factory, status: :created, location: @factory }
      else
        format.html { render action: "new" }
        format.json { render json: @factory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /factories/1
  # PUT /factories/1.json
  def update
    @factory = Factory.find(params[:id])

    respond_to do |format|
      if @factory.update_attributes(params[:factory])
		  format.html { redirect_to @factory, notice: t('actions.factory.notice.updated') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @factory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /factories/1
  # DELETE /factories/1.json
  def destroy
    @factory = Factory.find(params[:id])
    @factory.destroy

    respond_to do |format|
      format.html { redirect_to factories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/factories_helper.rb
module FactoriesHelper
end

app/views/factories/_form.html.erb
<%= form_for(@factory) do |f| %>
  <%= f.error_messages :class =>  "error_explanation",  :id => "error_explanation" %>
  <div class="field">
    <%= f.label :factory_num %><br />
    <%= f.number_field :factory_num %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :ceo_name %><br />
    <%= f.text_field :ceo_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/factories/edit.html.erb
<h1><%= t('actions.factory.edit', :item => @factory.name) %></h1>

<%= render 'form' %>

<%= link_to t('links.show'), @factory %> |
<%= link_to t('links.back'), factory_path %>

app/views/factories/index.html.erb
<h1><%= t('actions.factory.index') %></h1>

<% if @factories.empty? %>
<p><%= t('empty')%></p>
<% else %>

<table>
  <tr>
    <th><%= t('activerecord.attributes.factory.factory_num') %></th>
    <th><%= t('activerecord.attributes.factory.name') %></th>
    <th><%= t('activerecord.attributes.factory.address') %></th>
    <th><%= t('activerecord.attributes.factory.ceo_name') %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @factories.each do |factory| %>
  <tr>
    <td><%= factory.factory_num %></td>
    <td><%= factory.name %></td>
    <td><%= factory.address %></td>
    <td><%= factory.ceo_name %></td>
    <td><%= link_to t('links.show'), factory %></td>
    <td><%= link_to t('links.edit'), edit_factory_path(factory) %></td>
    <td><%= link_to t('links.delete'), factory, confirm: t('actions.confirm'), method: :delete %></td>
  </tr>
<% end %>
</table>
<% end %>

<br />

<%= link_to t('actions.factory.new'), new_factory_path %>

app/views/factories/new.html.erb
<h1><%= t('actions.factory.new') %></h1>

<%= render 'form' %>

<%= link_to t('links.back'), factories_path %>

app/views/factories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<b><%= t('activerecord.attributes.factory.factory_num') %>:</b>
	<%= @factory.factory_num %>
</p>

<p>
	<b><%= t('activerecord.attributes.factory.name') %>:</b>
	<%= @factory.name %>
</p>

<p>
	<b><%= t('activerecord.attributes.factory.address') %>:</b>
	<%= @factory.address %>
</p>

<p>
	<b><%= t('activerecord.attributes.factory.ceo_name') %>:</b>
	<%= @factory.ceo_name %>
</p>

<p>
	<b><%= t('activerecord.attributes.factory.departments') %>:</b>
	<%= @factory.departments.count %>
	<% unless @factory.departments.empty? %>
		<table summary="Factory departments">
			<tr>
				<th><%= t('activerecord.attributes.department.name') %></th>
				<th><%= t('activerecord.attributes.department.chief_name') %></th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
			<%= render @departments %>
		</table>
		<%= will_paginate @departments %>
	<% end%>
	<%= link_to t('actions.department.new', :item => ''), new_factory_department_path(@factory.id) %>
</p>

<%= link_to t('links.edit'), edit_factory_path(@factory) %> |
<%= link_to t('links.back'), factories_path %>