config/routes.rb
Zavod::Application.routes.draw do
	match '/contact', :to => 'pages#contact'

	match '/about',   :to => 'pages#about'

	root :to => 'pages#home'

	get "reports/parts"

	get "reports/deliveries"

	resources :suppliers do
		resources :parts
	end

	resources :products do
		resources :parts #, :except => [ :edit, :new, :create, :destroy, :update ]
		member do
			get :add_part
			put :assign_part, :free_part
		end
	end

	resources :factories do
		resources :departments do
			resources :products
		end
	end

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id            :integer(4)      not null, primary key
#  department_id :integer(4)
#  name          :string(255)
#  weight        :integer(10)
#  created_at    :datetime        not null
#  updated_at    :datetime        not null
#

class Product < ActiveRecord::Base
	has_many :parts
	belongs_to :department

	validates :name, :presence => true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	# GET /products
	# GET /products.json
	def index
		@products = Product.all

		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @products }
		end
	end

	# GET /products/1
	# GET /products/1.json
	def show
		@product = Product.find(params[:id])
		@product_parts = @product.parts.paginate(:page => params[:page])
		@department = @product.department
		@factory = @department.factory

		respond_to do |format|
			format.html # show.html.erb
			format.json { render json: @product }
		end
	end

	# GET /products/new
	# GET /products/new.json
	def new
		@product = Product.new
		@parts = Part.all

		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @product }
		end
	end

	# GET /products/1/add_part
	def add_part
		@product = Product.find(params[:id])
		@parts = Part.all
	end

	# PUT /products/1
	# PUT /products/1.json
	def assign_part
		@product = Product.find(params[:id])
		@part = Part.find(params[:product][:parts])
		
		respond_to do |format|
			if @part.update_attributes({:product_id => @product.id})
				format.html { redirect_to @product, notice: t('actions.product.notice.created') }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @product.errors, status: :unprocessable_entity }
			end
		end
	end
	
	def free_part
		@part = Part.find(params[:part])
		@product = Product.find(params[:id])
		
		respond_to do |format|
			if @part.update_attributes({:product_id => nil})
				format.html { redirect_to @product, notice: t('actions.product.notice.updated') }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @product.errors, status: :unprocessable_entity }
			end
		end
	end
	# GET /products/1/edit
	def edit
		@product = Product.find(params[:id])
		@parts = Part.all
	end

	# POST /products
	# POST /products.json
	def create
		@product = Product.new(params[:product])

		respond_to do |format|
			if @product.save
				format.html { redirect_to @product, notice: t('actions.product.notice.created') }
				format.json { render json: @product, status: :created, location: @product }
			else
				format.html { render action: "new" }
				format.json { render json: @product.errors, status: :unprocessable_entity }
			end
		end
	end

	# PUT /products/1
	# PUT /products/1.json
	def update
		@product = Product.find(params[:id])

		respond_to do |format|
			if @product.update_attributes(params[:product])
				format.html { redirect_to @product, notice: t('actions.product.notice.updated') }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @product.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /products/1
	# DELETE /products/1.json
	def destroy
		@product = Product.find(params[:id])
		@product.destroy

		respond_to do |format|
			format.html { redirect_to products_url }
			format.json { head :no_content }
		end
	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <%= f.error_messages :class =>  "error_explanation",  :id => "error_explanation" %>
  <div class="field">
    <%= f.label :department_id %><br />
	<%= f.collection_select( :department_id, Department.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product_part.html.erb
<tr>
	<td><%= part.part_number %></td>
	<td><%= part.name %></td>
<!-- 	<td><%= if part.product then part.product.name else t('none') end %></td> -->
	<td><%= part.weight %></td>
	<td><%= part.dimensions %></td>
	<td><%= if part.supplier then part.supplier.name else t('none') end %></td>
	<td><%= l part.delivery_date %></td>
	<td><%= link_to t('links.show') , supplier_part_path(part.supplier_id, part) %></td>
<!-- 	<td><%= link_to 'Edit', edit_supplier_part_path(part.supplier_id, part) %></td> -->
	<td><%= link_to t('links.remove'), free_part_product_path(part.product_id, :part => part), confirm: 'Are you sure?', :method => :put %></td>
</tr>

app/views/products/add_part.html.erb
<h1><%= t('actions.product.add_part', :item => @product.name) %></h1>

<%= form_for(@product, :url => { :action => "assign_part" }) do |f| %>
  <%= f.error_messages :class =>  "error_explanation",  :id => "error_explanation" %>
  <div class="field">
    <%= f.label :parts %><br />
	<%= f.collection_select( :parts, Part.all, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to t('links.show'), @product %> |
<%= link_to t('links.back'), products_path %>

app/views/products/edit.html.erb
<h1><%= t('actions.product.edit', :item => @product.name) %></h1>

<%= render 'form' %>

<%= link_to t('links.show'), @product %> |
<%= link_to t('links.back'), products_path %>

app/views/products/index.html.erb
<h1><%= t('actions.product.index') %></h1>

<% if @products.empty? %>
<p>None</p>
<% else %>
<table>
  <tr>
    <th><%= t('activerecord.attributes.department.factory_id') %></th>
    <th><%= t('activerecord.attributes.product.department_id') %></th>
    <th><%= t('activerecord.attributes.product.name') %></th>
    <th><%= t('activerecord.attributes.product.weight') %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= if product.department && product.department.factory then product.department.factory.name else '#error' end%></td>
    <td><%= if product.department then product.department.name else '#error' end %></td>
    <td><%= product.name %></td>
    <td><%= product.weight %></td>
    <td><%= link_to t('links.show'), product %></td>
    <td><%= link_to t('links.edit'), edit_product_path(product) %></td>
    <td><%= link_to t('links.delete'), product, confirm: t('actions.confirm'), method: :delete %></td>
  </tr>
<% end %>
</table>
<% end %>

<br />

<%= link_to t('actions.product.new'), new_product_path %>

app/views/products/new.html.erb
<h1><%= t('actions.product.new') %></h1>

<%= render 'form' %>

<%= link_to t('links.back'), products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= t('activerecord.attributes.department.factory_id') %>:</b>
  <%= @factory.name %>
</p>

<p>
  <b><%= t('activerecord.attributes.product.department_id') %>:</b>
  <%= @department.name %>
</p>

<!--<p>
  <b><%= t('activerecord.attributes.product.name') %>:</b>
  <%= @product.name %>
</p>-->

<p>
  <b><%= t('activerecord.attributes.product.weight') %>:</b>
  <%= @product.weight %>
</p>

<p>
<b><%= t('activerecord.attributes.product.parts') %>:</b>
<%= @product.parts.count %>
<% unless @product.parts.empty? %>
	<table summary="Product parts">
		<tr>
			<th><%= t('activerecord.attributes.part.part_number') %></th>
			<th><%= t('activerecord.attributes.part.name') %></th>
<!-- 			<th><%= t('activerecord.attributes.part.product_id') %></th> -->
			<th><%= t('activerecord.attributes.part.weight') %></th>
			<th><%= t('activerecord.attributes.part.dimensions') %></th>
		    <th><%= t('activerecord.attributes.part.supplier_id') %></th>
			<th><%= t('activerecord.attributes.part.delivery_date') %></th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
		<%= render :partial => 'product_part', :collection => @product_parts, :as => :part %>
	</table>
	<%= will_paginate @product_parts %>
<% end%>
<%= link_to t('actions.product.add_part', :item => ''), add_part_product_path(@product.id) %>
</p>

<%= link_to t('links.edit'), edit_product_path(@product) %> |
<%= link_to t('links.back'), products_path %>