config/routes.rb
Zavod::Application.routes.draw do
	match '/contact', :to => 'pages#contact'

	match '/about',   :to => 'pages#about'

	root :to => 'pages#home'

	get "reports/parts"

	get "reports/deliveries"

	resources :suppliers do
		resources :parts
	end

	resources :products do
		resources :parts #, :except => [ :edit, :new, :create, :destroy, :update ]
		member do
			get :add_part
			put :assign_part, :free_part
		end
	end

	resources :factories do
		resources :departments do
			resources :products
		end
	end

end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
			<li><%= link_to t('links.nav.about'), about_path %></li>
			<li><%= link_to t('links.nav.contact'), contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
<!-- 			<%= image_tag("logo.png", :alt => "Sample App", :class => "round") %> -->
	<div class="round logo">
		<a href="<%= root_path%>">
			<h1 style="margin: 0; color: #FFF">Zavod</h1>
			<h2 style="margin: 0; color: #FFF">Test App</h2>
		</a>
	</div>
	<nav class="round">
		<ul>
			<li>
				<%= link_to t('links.nav.edit'), '#' %>
				<ul>
					<li><%= link_to t('links.nav.factories'), factories_path %></li>
					<li><%= link_to t('links.nav.products'), products_path %></li>
					<li><%= link_to t('links.nav.suppliers'), suppliers_path %></li>
				</ul>
			</li>
			<li>
				<%= link_to t('links.nav.reports'), '#' %>
				<ul>
					<li><%= link_to t('links.nav.parts'), reports_parts_path %></li>
<!-- 					<li><%= link_to "Deliveries", reports_deliveries_path %></li> -->
				</ul>
			</li>
		</ul>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<!-- <%= stylesheet_link_tag 'custom', :media => 'screen' %> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= title %></title>
<%= csrf_meta_tags %>
<%= render 'layouts/stylesheets' %>
<%= stylesheet_link_tag "application" %>
<%= javascript_include_tag "application" %>
</head>
<body>
	<div class="container">
	<%= render 'layouts/header' %>
	<section class="round">
		<%= yield %>
	</section>
	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>